apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-system
  namespace: default
data:
  config: |
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.49.2-192.168.49.2